### ISSUE TITLE
bet 6

### ISSUE THREAD

**Issue by MaCo7** [contao/contao-manager#121]
Nach automatischem Update auf die beta 6 des contao-manager.phar funktioniert Paketaktualiserung / löschen / Cache leeren, bei mir gar nichtmehr. Folgendes im Log:

```
[27-Jun-2017 16:16:12 Europe/Berlin] [2017-06-27 16:16:12] app.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Uncaught Error: Call to a member function removeAssets() on null in phar:///html/web/contao-manager.phar.php/api/Controller/TaskController.php:109 Stack trace: #0 [internal function]: Contao\ManagerApi\Controller\TaskController->deleteTask() #1 phar:///html/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #2 phar:///html/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 phar:///html/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(171): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 phar:///html/web/contao-manager.phar.php/web/api.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #5 [internal function]: unknown() #6 /html/web/contao-manager.phar.php(100): Phar::webPhar('contao-manager...." at phar:///html/web/contao-manager.phar.php/api/Controller/TaskController.php line 109 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Uncaught Error: Call to a member function removeAssets() on null in phar:///html/web/contao-manager.phar.php/api/Controller/TaskController.php:109\nStack trace:\n#0 [internal function]: Contao\\ManagerApi\\Controller\\TaskController->deleteTask()\n#1 phar:///html/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array)\n#2 phar:///html/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#3 phar:///html/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(171): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#4 phar:///html/web/contao-manager.phar.php/web/api.php(19): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#5 [internal function]: unknown()\n#6 /html/web/contao-manager.phar.php(100): Phar::webPhar('contao-manager.... at phar:///html/web/contao-manager.phar.php/api/Controller/TaskController.php:109)"} []
```

**Comment by aschempp** [comment]
der Fehler wurde in der Beta7 behoben.
