### ISSUE TITLE
Problem Hetzner Beta 7

### ISSUE THREAD

**Issue by standing-bear** [contao/contao-manager#125]
Leider wurde "Problem Hetzner Beta 4" ja bereits geschlossen, da das Problem angeblich behoben ist.

Also bei mir läuft die Beta7 auf Hetzner Level 4 nicht!?

```
Using version ^2.0 for madeyourday/contao-rocksolid-slider
/usr/www/users/pigs/cto44/composer.json has been updated
Loading composer repositories with package information
Updating dependencies

Killed

Process terminated with exit code 137
Reason: Kill (terminate immediately)
```

Das kommt bei allen Paketen, die ich installieren wollte.

**Comment by aschempp** [comment]
Ist die initiale Installation denn durchgelaufen?

**Comment by standing-bear** [comment]
Ja, ist komplett problemlos durchgelaufen. Nur Packages kann ich nicht installieren.

**Comment by aschempp** [comment]
dann gibt es auf dem Server vermutlich eine Prozessüberwachung welche die Installation aufgrund von Laufzeit oder Memory-Limit beendet 😢

**Comment by standing-bear** [comment]
Ich habe alle Werte (z. B. memory_limit) über die konsole-h bei Hetzner auf das maximal Mögliche gesetzt. Geht aber trotzdem nicht. Ich bekomme den Fehler übrigens auch, wenn ich einfach auf "Pakete aktualisieren" klicke.

Beim Installations-Versuch des Rocksolid-Sliders kommt manchmal auch folgendes, wobei ich mich frage, woher die Meldungen mit dem "dma_elementgenerator" kommen, der ja noch gar nicht installiert ist?!

```
Using version ^2.0 for madeyourday/contao-rocksolid-slider
/usr/www/users/pigs/cto44/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dma/dma_elementgenerator 1.0.3 requires contao/core >=3.0,<3.5 -> satisfiable by contao/core[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5].
    - dma/dma_elementgenerator 1.0.4 requires contao/core 3.* -> satisfiable by contao/core[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.5.1, 3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.18, 3.5.19, 3.5.2, 3.5.20, 3.5.21, 3.5.22, 3.5.23, 3.5.24, 3.5.25, 3.5.26, 3.5.27, 3.5.3, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9].
    - dma/dma_elementgenerator 1.0.5 requires contao/core 3.* -> satisfiable by contao/core[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.5.1, 3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.18, 3.5.19, 3.5.2, 3.5.20, 3.5.21, 3.5.22, 3.5.23, 3.5.24, 3.5.25, 3.5.26, 3.5.27, 3.5.3, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.0.0].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.0.1].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.0.2].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.0.3].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.0.4].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.0.5].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.0.6].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.1.0].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.1.1].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.1.2].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.1.3].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.1.4].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.1.5].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.0].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.1].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.10].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.11].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.12].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.13].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.14].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.15].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.16].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.17].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.18].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.19].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.2].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.20].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.21].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.3].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.4].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.5].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.6].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.7].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.8].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.2.9].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.0].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.1].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.2].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.3].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.4].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.5].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.6].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.3.7].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.4.0].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.4.1].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.4.2].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.4.3].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.4.4].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.4.5].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.0].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.1].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.10].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.11].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.12].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.13].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.14].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.15].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.16].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.17].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.18].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.19].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.2].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.20].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.21].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.22].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.23].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.24].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.25].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.26].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.27].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.3].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.4].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.5].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.6].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.7].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.8].
    - madeyourday/contao-rocksolid-slider v2.0.0 conflicts with contao/core[3.5.9].
    - Installation request for madeyourday/contao-rocksolid-slider ^2.0 -> satisfiable by madeyourday/contao-rocksolid-slider[v2.0.0].
    - Installation request for dma/dma_elementgenerator ^1.0 -> satisfiable by dma/dma_elementgenerator[1.0.3, 1.0.4, 1.0.5].


Installation failed, reverting /usr/www/users/pigs/cto44/composer.json to its original content.
--------------------------------------------------------
Exception occured: Error: command exit code was 2
#0 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/usr/www/users/...')
#3 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(83): Tenside\Core\Task\Runner->run('/usr/www/users/...')
#4 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/www/users/pigs/cto44/web/contao-manager.phar.php(55): require('phar:///usr/www...')
#12 {main}
Chained exception: Error: command exit code was 2
#0 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/usr/www/users/...')
#3 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(83): Tenside\Core\Task\Runner->run('/usr/www/users/...')
#4 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/www/users/pigs/cto44/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/www/users/pigs/cto44/web/contao-manager.phar.php(55): require('phar:///usr/www...')
#12 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

**Comment by aschempp** [comment]
Das ist kein Server-Problem! Lies die Meldung genau:

> Your requirements could not be resolved to an installable set of packages.
>    - dma/dma_elementgenerator 1.0.3 requires contao/core >=3.0,<3.5

Du hast versucht den dma_elementgenerator zu installieren, welcher nur mit Contao 3 funktioniert.

**Comment by standing-bear** [comment]
Das ist ja genau das Ding ... ich habe gar nicht versucht, den dma_elementgenerator zu installieren. Ich weiß nicht, woher der kommt?!

**Comment by aschempp** [comment]
Vielleicht aus dem Rocksolid Slider, auf jeden Fall ist das kein Manager-Problem (das wir lösen könnten).

**Comment by heimseiten** [comment]
Beim "Level 4" Paket kann ich den Fehler bestätigen. Eine frische Installation läuft durch, aber beim Aufruf von "Pakete aktualisieren" kommt die Meldung: "Process terminated with exit code 137"

Die Tests aus dem ersten Issue [(#109)](https://github.com/contao/contao-manager/issues/109) habe ich auf einem "Managed Server" durchgeführt, wo alles, mit den gleichen Einstellungen wie auf dem "Level 4" Paket, funktioniert. Beides getestet mit Version 1.0.0-beta8.

Level 4:
<img width="600" alt="bildschirmfoto 2017-07-13 um 08 53 28" src="https://user-images.githubusercontent.com/6552484/28154826-0680270a-67ac-11e7-8390-09cf1fc4ae4f.png">
<img width="600" alt="bildschirmfoto 2017-07-13 um 08 53 50" src="https://user-images.githubusercontent.com/6552484/28154920-7a3464d6-67ac-11e7-99e2-69d0edb07743.png">

Managed Server:
<img width="600" alt="bildschirmfoto 2017-07-13 um 09 17 43" src="https://user-images.githubusercontent.com/6552484/28154861-37ee9d4e-67ac-11e7-8d1a-b083cec9c78d.png">
<img width="600" alt="bildschirmfoto 2017-07-13 um 09 18 29" src="https://user-images.githubusercontent.com/6552484/28154879-4d2a39c0-67ac-11e7-9825-23d8cd063660.png">

**Comment by standing-bear** [comment]
Hi Andreas,

ja, genau so ist es. Das System merkt sich offenbar sogar, was ich einmal versucht habe zu installieren, z. B. den dma_elementgenerator oder den RS-Slider, und versucht es jedesmal wieder. Auch Cache löschen hilft hier nichts. Ich brauche nur auf Pakete aktualisieren zu klicken und er versucht immer wieder den RS-Slider und den dma_elementgenerator zu installieren, was immer fehlschlägt.

Aktuell sind jedenfalls nur die Contao Core Packages installiert ...

![contao-manager](https://user-images.githubusercontent.com/13131551/28155347-90307e8a-67ae-11e7-871b-573078b1c485.jpg)

**Comment by heimseiten** [comment]
Es scheint auch beim "Level 4" Paket manchmal zu funktionieren. Kann leider keine Regelmäßigkeit feststellen :/

**Comment by heimseiten** [comment]
Mit der 1.0.0-beta10 bekomme ich auf einem "Managed Server" mit 12 GB zugewiesenem Arbeitsspeicher und 10 Minuten Timeout fast immer "Process terminated with exit code 137".

Gibt es eine Möglichkeit herauszufinden, was den Prozess beendet? Sodass man Hetzner bitten könnte das auszuschalten.

Gerne kann ich auch eine Testumgebung bereitstellen.

Vielen Dank im Voraus.

**Comment by aschempp** [comment]
Exit Code 137 ist ein [SIGKILL](https://de.wikipedia.org/wiki/SIGKILL) Befehl, welcher von einem anderen Prozess an den Contao Manager gesendet wird. Es sieht also danach aus als ob auf dem Server eine "Überwachungssoftware" läuft welche den Manager beendet, z.B. weil er zu lange läuft oder zu viel Memory benötigt. Dass kann allerdings nur Hetzner feststellen. Auf einem Linux-System müsste es dazu Logdateien geben, das konkrete Setup kennt aber nur Hetzner…

**Comment by heimseiten** [comment]
Als Antwort von Hetzer habe ich bekommen, dass der PHP CLI Prozess von der Überwachung des Servers aufgrund des verbrauchten Arbeitsspeichers beendet wird. Dort ist als Limit standardmässig 500 MB eingestellt. Wenn man das ändern möchte, muss ein unterschriebenes Formular eingereicht werden.

Dem Manager ein Limit von 500 MB zu geben ist nicht möglich, oder?

Wie viel MB würden dem Manager denn auf jeden Fall ausreichen?

**Comment by aschempp** [comment]
> Wie viel MB würden dem Manager denn auf jeden Fall ausreichen?

Das lässt sich leider nicht genau sagen, denn es hängt von den installierten Paketen ab. Standardmässig versucht Composer (und daran orientiert sich der Contao Manager) 1.5GB zu reservieren. Das Memory-Problem lässt sich am Ende wohl wirklich nur mit einem Cloud Resolver lösen 😢

**Comment by standing-bear** [comment]
Das hört sich gerade irgendwie nicht wirklich gut an?! Eine Erläuterung wäre aber hilfreich. Was genau ist ein Cloud Resolver, und was bedeutet das für Contao bzw. den Manager insgesamt? Ich bin seit fast 20 Jahren bei Hetzner und habe die unterschiedlichsten Systeme dort laufen und noch nie ernsthafte Probleme gehabt. Es kann doch irgendwie nicht sein, dass der Contao Manager derartige Ressourcen benötigt, dass er auf einem Server eines großen Providers nicht läuft?!? Ich - und ich denke viele andere Entwickler auch - warte/n auf eine Lösung für den Contao Manager, um endlich komfortabel Contao 4 einsetzen zu können. Ohne diesen, wäre Contao insgesamt wirklich fraglich, weil einfach zu umständlich. Für mich wäre das ein echter Rückschritt, wenn das nicht funktionieren würde. Eine andere Sache ist auch, dass composer auf Level 19 Servern bei Hetzner ja problemlos läuft, der Contao Manager aber nicht?! Kann also doch nicht wirklich nur an den domposer-Anforderungen liegen.

**Comment by aschempp** [comment]
Es ist sehr wahrscheinlich tatsächlich so, dass Hetzner und andere Anbieter die Memory-Limits für Composer explizit erhöht haben. Du kannst mal versuchen die `contao-manager.phar.php` in `composer.phar` umzubenennen und auf der Kommandozeile auszuführen 😉

**Comment by standing-bear** [comment]
Scheint nicht der Fall zu sein. Ich kann maximal 384MB als Memory Limit bei Level 19 anfordern. Das scheint dann ja hinten und vorne nicht zu reichen. Heißt das also, dass Contao mittels Manager nur noch bei dedizierten Providern lauffähig sein wird?

**Comment by aschempp** [comment]
Das ist nicht korrekt. Es gibt jede Menge Provider die problemlos funktionieren, weil sie das Memory-Limit auf Kommandozeile nicht anwenden. Beachte nochmals: Memory-Limit des Hosting-Packet hat in 90% der Fälle **nichts** mit der Kommandozeile zu tun.

Ausserdem, jeder Hoster der die Kommandozeile unterstützt und auf dem Composer genutzt werden soll – und das werden sehr viele sein – werden dasselbe Problem lösen müssen. Es hat nichts mit dem Contao Manager an-sich zu tun.

**Comment by standing-bear** [comment]
Verstehe ich leider immer noch nicht so ganz. Ich will ja nicht auf Kommandozeile arbeiten, sondern mit dem Manager?!

**Comment by standing-bear** [comment]
Hetzner hat für meinen Account zu Testzwecken auf 2GB hochgesetzt. Die Fehlermeldungen bleiben jedoch gleich. Ich denke, das Memory Limit kann daher nicht das wirkliche bzw. alleinige Problem des Contao-Managers sein?!

**Comment by standing-bear** [comment]
Ja, ich hatte nach Andreas Anregung die contao-manager.phar.php in composer.phar umbenannt. Bei "php composer.phar update" bekomme ich dann aber die Meldung
`"Command "update" is not defined. Did you mean this? self-update`
Kenne mich mit composer leider bisher nicht weiter aus?!

**Comment by xchs** [comment]
Du könntest das Composer Update so ausführen:
```console
php contao-manager.phar.php composer update
```

**Comment by standing-bear** [comment]
Super, danke, hat funktioniert ;-))

**Comment by standing-bear** [comment]
Habe jetzt mal eine ganz neue Contao 4.4 per Contao-Manager installiert. Da wird angezeigt 106 installs. Alles funktioniert einwandfrei, läuft komplett durch. Wenn ich über den Manager dann unmittelbar nach der Installation auf "Pakete aktualisieren" klicke, wo also im Prinzip ja nichts zu aktualisieren ist, kommt nach einer Weile "Process terminated with exit code 137".

Das kann doch also unmöglich ein Memory-Problem sein, sonst würde doch ganz sicher die Installation über den Manager schon scheitern. Was läuft bei der Aktualisierung durch den Manager also anders, dass es zu diesem Fehler kommt?

Über SSH kann ich die Aktualisierung problemlos durchführen. Das kann man natürlich machen, aber dann ist der Manager ja im Prinzip witzlos!?

**Comment by aschempp** [comment]
Bei der Installation werden keine Abhängigkeiten aufgelöst, daher funktioniert das. Es liegt am Memory ;-)

**Comment by standing-bear** [comment]
Das heißt also, Hetzner kommt als Contao-Provider nicht mehr in Frage, wenn man den Contao-Manager nutzen will??? Hetzner sagt, es liegt nicht am Memory. Muss ich jetzt den Provider wechseln oder das CMS?

**Comment by standing-bear** [comment]
Welches Memory ist denn eigentlich gemeint? Hetzner hatte auf meine Anfrage hin temporär das PHP memory_limit auf 2GB hochgesetzt. Aber auch damit hat es nicht funktioniert?!

**Comment by aschempp** [comment]
Wie bereits erwähnt, es geht um Memory Limit auf der Kommandozeile. Und es ist nicht das PHP Memory Limit, denn dann würde von PHP eine entsprechende Meldung kommen.

Falls du einen guten Kontakt zu Hetzner hast, der nicht gerade First Level ist und keine Ahnung hat, dann kann er mich gerne kontaktieren. Wäre schön wenn Hetzner funktionieren würde, aber es liegt an deren Hosting und nicht am Manager.

**Comment by standing-bear** [comment]
Das Problem ist ja nicht nur Hetzner. Nahezu alle meine Contao-Kunden haben relativ einfache Shared Host Accounts z. B. bei 1&1, Strato, Host Europe, United Domains, Domain Factory, Hetzner, Hoststar. Der Manager funktioniert schlicht gesagt nirgends auf diesen Systemen. Wenn das in Zukunft nicht mehr funktionieren sollte, wäre das für Contao ein schlechtes Zeichen, d. h. einfach nicht mehr einsetzbar. Es kann sich ja nicht jeder Kunde einen eigenen Server buchen, damit seine Website noch läuft.

 

Von: Andreas Schempp [mailto:notifications@github.com] 
Gesendet: Montag, 2. Oktober 2017 09:54
An: contao/contao-manager <contao-manager@noreply.github.com>
Cc: standing-bear <info@mpme.de>; Author <author@noreply.github.com>
Betreff: Re: [contao/contao-manager] Problem Hetzner Beta 7 (#125)

 

Wie bereits erwähnt, es geht um Memory Limit auf der Kommandozeile. Und es ist nicht das PHP Memory Limit, denn dann würde von PHP eine entsprechende Meldung kommen.

Falls du einen guten Kontakt zu Hetzner hast, der nicht gerade First Level ist und keine Ahnung hat, dann kann er mich gerne kontaktieren. Wäre schön wenn Hetzner funktionieren würde, aber es liegt an deren Hosting und nicht am Manager.

**Comment by leofeyer** [comment]
Wie schon per Mail gesagt, ist der Manager momentan in der Beta-Phase und wir arbeiten mit den Hostern zusammen, um die Probleme zu beheben. Unser Ziel ist es, dass der Manger auf normalen Shared-Hostings läuft, was bei etlichen Anbietern auch schon der Fall ist.

Man braucht definitiv keinen eigenen Server, um Contao 4 zu installieren!

**Comment by standing-bear** [comment]
Alle klar, das klingt gut. Gibt es denn schon irgendwie eine Art Whitelist von Providern, bei denen der Manager auf einem einfachen Shared Host funktioniert? Ich habe bisher keinen geeigneten Provider gefunden, würde Contao 4 aber sehr gerne schon mal testen.

**Comment by Ainschy** [comment]
Im Shared Hosting bei Hetzner ist das Memory-Limit ein echtes Problem. Prozesse werden wie Oben  beschrieben gekillt, so das der CM im schlimmsten Fall den Status der Installation nicht eindeutig erfassen kann und weitere Arbeiten verweigert. Bei den Level 19 Produkten gibt es immerhin einen SSH Zugang, mit dessen Hilfe das composer update solange durchgeführt werden kann bis der Cache neu geschrieben ist.

Wäre es möglich dem CM eine Funktion zu geben, das dieser ein Update startet, auch der Status der Installation nicht eindeutig ist? Vllt. als URL Parameter?

**Comment by innoreq** [comment]
Bei unserem Level19-Hosting läuft der Contao-Manager im Browser ebenfalls nicht (Killed - 137, Hetzner). PHP-Settings zu maximieren brachte ebenfalls nichts. Auf der Kommandozeile (php composer.phar require...) läuft's aber problemlos. Auffällig bei uns ist, dass der Webserver derzeit (noch) auf PHP 5.6 konfiguriert ist, der Kommandozeilen-PHP aber 7.1 nutzt.

**Comment by heimseiten** [comment]
> Wäre es möglich dem CM eine Funktion zu geben, das dieser ein Update startet, auch der Status der Installation nicht eindeutig ist? Vllt. als URL Parameter?

Das wäre klasse! 

Vielleicht auch eine Einstellung, dass der Contao Manager evtl. fünf mal eine Aktualisierung anstößt und erst dann den Prozess abbricht. Und wenn es dann immer noch nicht funktioniert hat, sollte man, auch bei nicht eindeutigem Installationsstatus, eine weitere Paket-Aktualisierung anstoßen können.

Damit könnte man die Situation umgehen, dass ohne SSH auf ein Mal gar nichts mehr geht, "nur" weil die Aktualisierung nicht vollständig durchgelaufen ist.
