### ISSUE TITLE
world4you: Installation / Aktualiesierung und Pakete installieren funktioniert nicht

### ISSUE THREAD

**Issue by pressi** [contao/contao-manager#169]
Hallo!

Habe auf einem World4You Hosting versucht mit dem Contao Manager Contao zu installieren gab immer einen Fehler.
Habe dann Contao manuell hochgeladen.

Jetzt habe ich beim installieren von Packages immer einen Fehler in der Konsole des Contao Managers:

Das Package scheint installiert worden zu sein, da beim 2. Versuch die Meldung kommt "Nothing to install or update", wie unten zu sehen.
Das Package erscheint aber auch nicht in der Liste vom Contao Manager, bei einer anderen Installation auf einem anderem Hosting (anderer Anbieter, all-inkl) wird dieses aber in der Liste dargestellt.

```
/home/.sites/100/site3099888/web/dev/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Nothing to install or update
Generating optimized autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

Installation failed, reverting /home/.sites/100/site3099888/web/dev/composer.json to its original content.
--------------------------------------------------------
Exception occured: The php executable could not be found.
#0 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/home/.sites/10...')
#3 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/home/.sites/10...')
#4 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php(55): require('phar:///home/.s...')
#12 {main}
Chained exception: The php executable could not be found.
#0 /home/.sites/100/site3099888/web/dev/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(72): Contao\ManagerBundle\Composer\ScriptHandler::executeCommand('contao:install-...', Object(Composer\Script\Event))
#1 /home/.sites/100/site3099888/web/dev/vendor/contao/manager-bundle/src/Composer/ScriptHandler.php(35): Contao\ManagerBundle\Composer\ScriptHandler::addWebEntryPoints(Object(Composer\Script\Event))
#2 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication(Object(Composer\Script\Event))
#3 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Contao\\ManagerB...', 'initializeAppli...', Object(Composer\Script\Event))
#4 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', false)
#6 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/RequireCommand.php(180): Composer\Installer->run()
#7 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Composer\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#8 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#9 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#10 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#11 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/home/.sites/10...')
#12 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/home/.sites/10...')
#13 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/.sites/100/site3099888/web/dev/web/contao-manager.phar.php(55): require('phar:///home/.s...')
#21 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

LG

**Comment by xchs** [comment]
Wie lautet denn der Pfad zur PHP Binary? Was steht denn in `contao-manager/manager.json` in der Zeile für `php_cli`? Laut [Wiki](https://github.com/contao/contao-manager/wiki/World4You) sollte es mit
```
"php_cli": "\/user\/bin\/php7",
```
eigentlich funktionieren.

**Comment by pressi** [comment]
Der Pfad war: `"php_cli": "\/usr\/bin\/php71",`
Habe ihn in "php7" geändert, aber das Problem besteht weiterhin.
Es funktioniert mit PHP 7 und PHP 7.1 nicht.

**Comment by alexisRippstein** [comment]
> Es funktioniert mit PHP 7 und PHP 7.1 nicht.

Bei mir hat es mit `/usr/bin/php71` unter der Version 1.0.0-**beta11** funktioniert!

**Comment by SyZn** [comment]
Was genau ist der Fehler den du (@pressi ) im ContaoManager bekommst?
Ich habe selber versucht bei world4you Contao per CM zu installieren. Komme auch in die Install-Routine hinein, wo auch der composer die Arbeit beginnt. Allerdings kann er diese nicht abschließen. Meine Vermutung ist, dass die `execution_time` und das `memory_limit` dies verhindern. Kann mir irgendwer sagen, was hier die "ungefähren Systemvoraussetzungen" sind? Ich meine damit, wie lange braucht eine Standardinstallation mit composer bzw. wieviel memory wird ca. benötigt? Mir ist durchaus klar das die `execution_time` von der zur Verfügung gestellten Netzwerkverbindung abhängt. Dennoch würde mich eine ungefähre Zeit interessieren, damit ich überprüfen kann ob die `execution_time` bzw. das `memory_limit` der Grund für die Installationsprobleme sind. (Ich würde es ja gerne selber messen, hab aber im Moment keinen entsprechenden Server zur Verfügung ;( ).

**Comment by jankout** [comment]
https://github.com/contao/contao-manager/issues/218

**Comment by Toflar** [comment]
Today, we released version 1.0.0 stable. This version also ships with Composer Cloud that allows resolving of the dependencies on our servers. You can enable it in the hosting configuration. Try using it and see if that solves the issue and reopen if you still have the issue.

----

Wir haben heute Version 1.0.0 stable veröffentlicht. Diese Version bringt auch die Composer Cloud mit und ermöglicht die Abhängigkeitsauflösung auf unseren Servern. Sie kann bei den Hosting-Einstellungen aktiviert werden. Bitte damit erneut versuchen und Ticket wiedereröffnen, falls das Problem weiterhin besteht.
