### ISSUE TITLE
Error after auto-update

### ISSUE THREAD

**Issue by stefanschleich** [contao/contao-manager#176]
After logging into the manager for an existing contao 4.4.8. instance today I got an error 500 overlay visible in the browser. I panicked and forgot to take a screenshot, but you can find the log-output below. After manually reloading the manager-URL I saw another overlay stating that the update was successful (but with an empty console window). After closing the overlay I had to choose a hosting provider and there were several checks performed with a positive result. After that I could normally use the manager again.

Apart from the error the fact that I didn't know there would be an update and there was no explanation what's going to happen really scared me. I think the UX of the update process should be revised to make it more clear what's going to happen and what could go wrong.

Here's the part from the logfile (with user and env data removed):

```[01-Dec-2017 13:34:05 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Contao\ManagerApi\Process\ConsoleProcessFactory::__construct() must be an instance of Contao\ManagerApi\System\ServerInfo, instance of Contao\ManagerApi\Config\ManagerConfig given, called in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainer.php on line 765 and defined in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Process/ConsoleProcessFactory.php:50
Stack trace:
#0 phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainer.php(765): Contao\ManagerApi\Process\ConsoleProcessFactory->__construct(Object(Contao\ManagerApi\ApiKernel), Object(Contao\ManagerApi\Config\ManagerConfig), Object(Contao\ManagerApi\Process\ServerInfo), Object(Symfony\Bridge\Monolog\Logger))
#1 phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/vendor/symfony/dependency-injection/Container.php(331): apiProdProjectContainer- in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Process/ConsoleProcessFactory.php on line 50
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] request.INFO: Matched route "task_get". {"route":"task_get","route_parameters":{"_controller":"contao_manager.controller.tasks:getTask","_route":"task_get"},"request_uri":"https://URL_REMOVED/contao-manager.phar.php/api/task?_locale=de","method":"GET"} []
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":1} []
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"USER_REMOVED\", authenticated=true, roles=\"\"))","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[01-Dec-2017 13:34:05 Europe/Berlin] [2017-12-01 13:34:05] app.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Uncaught TypeError: Argument 2 passed to Contao\ManagerApi\Process\ConsoleProcessFactory::__construct() must be an instance of Contao\ManagerApi\System\ServerInfo, instance of Contao\ManagerApi\Config\ManagerConfig given, called in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainer.php on line 765 and defined in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Process/ConsoleProcessFactory.php:50 Stack trace: #0 phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainer.php(765): Contao\ManagerApi\Process\ConsoleProcessFactory->__construct(Object(Contao\ManagerApi\ApiKernel), Object(Contao\ManagerApi\Config\ManagerConfig), Object(Contao\ManagerApi\Process\ServerInfo), Object(Symfony\Bridge\Monolog\Logger)) #1 phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/vendor/symfony/dependency-injection/Container.php(331): apiProdProjectContainer-" at phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Process/ConsoleProcessFactory.php line 50 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Uncaught TypeError: Argument 2 passed to Contao\\ManagerApi\\Process\\ConsoleProcessFactory::__construct() must be an instance of Contao\\ManagerApi\\System\\ServerInfo, instance of Contao\\ManagerApi\\Config\\ManagerConfig given, called in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainer.php on line 765 and defined in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Process/ConsoleProcessFactory.php:50\nStack trace:\n#0 phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainer.php(765): Contao\\ManagerApi\\Process\\ConsoleProcessFactory->__construct(Object(Contao\\ManagerApi\\ApiKernel), Object(Contao\\ManagerApi\\Config\\ManagerConfig), Object(Contao\\ManagerApi\\Process\\ServerInfo), Object(Symfony\\Bridge\\Monolog\\Logger))\n#1 phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/vendor/symfony/dependency-injection/Container.php(331): apiProdProjectContainer- at phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/api/Process/ConsoleProcessFactory.php:50)"} []
[01-Dec-2017 13:34:06 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/vendor/symfony/debug/ErrorHandler.php:526
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/vendor/symfony/debug/ErrorHandler.php on line 526
[01-Dec-2017 13:34:06 Europe/Berlin] PHP Parse error:  syntax error, unexpected '<', expecting end of file in phar:///var/virtual/PATH_REMOVED/web/contao-manager.phar.php/vendor/symfony/debug/Exception/FatalErrorException.php on line 52
[01-Dec-2017 13:34:06 Europe/Berlin] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
```

**Comment by pagestyles** [comment]
Same here

**Comment by agoat** [comment]
In addition, I would prefer to be asked for a selfupdate before execution.

**Comment by dmolineus** [comment]
> In addition, I would prefer to be asked for a selfupdate before execution.

The CM is of the kind of software which knows what's good for you. ;-) Issue got closed for making auto update optimal. https://github.com/contao/contao-manager/issues/127

**Comment by agoat** [comment]
> The CM is of the kind of software which knows what's good for you. ;-)

And even microsoft has realized in Windows 10 that forced updates are not good and added possibility to postpone updates.

**Comment by aschempp** [comment]
Unfortunately, these issues are hard to fix or even impossible. The manager replaces itself during the update process, which means the application in memory differs from the application in the files. And when the application in memory tries to read files that are not yet in memory, this conflict appears. It does not really harm the system though. Still I would love to improve on that if there's any idea how…

**Comment by aschempp** [comment]
The self-update process has been revised in the latest version.
