### ISSUE TITLE
Contao install error: permisson denied

### ISSUE THREAD

**Issue by garyee** [contao/contao-manager#194]
I took the windows-phar from #66.
Tested on Windows 10, XAMPP (PHP 7.1.11, Apache 2.4).
Issue regarding Windows Support

At first I got an error because the symlinks could not be created. By Chance I had to install Git for Windows at that time and there is a option to install symlinks, so I got that out of the way.

I think that the console task started by the manager, does not have admin priviges. How can I enable that?

```
Exception occured: Project could not be created.
#0 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\InstallTask->doPerform()
#1 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('C:/xampp/htdocs...')
#2 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('C:/xampp/htdocs...')
#3 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\xampp\htdocs_contao_4\web\contao-manager.phar.php(55): require('phar://C:/xampp...')
#11 {main}

Chained exception: Warning: unlink(C:/xampp/htdocs_contao_4\install-5a3100f5dedd5\system\logs): Permission denied
#0 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/InstallTask.php(192): Tenside\Core\Task\Composer\InstallTask->moveFile(Object(Symfony\Component\Finder\SplFileInfo), 'C:/xampp/htdocs...', false, Object(Composer\IO\ConsoleIO))
#1 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/InstallTask.php(109): Tenside\Core\Task\Composer\InstallTask->moveFiles()
#2 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\InstallTask->doPerform()
#3 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('C:/xampp/htdocs...')
#4 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('C:/xampp/htdocs...')
#5 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar://C:/xampp/htdocs_contao_4/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs_contao_4\web\contao-manager.phar.php(55): require('phar://C:/xampp...')
#13 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

**Comment by aschempp** [comment]
I'm sorry but I can't give advice on a non-supported developer version. If you're a developer, feel free to debug the code, otherwise you will have to wait until windows support is fixed.

**Comment by bezin** [comment]
Same error as here: https://github.com/contao/contao-manager/issues/99 

@garyee Please be aware, that installing Contao itself via the Manager is not possible on Windows at the moment. However, it is possible to manage extensions via the Manager, if you download Contao manually as Zip archive and add the PHAR you already downloaded.
