### ISSUE TITLE
Fehler im CM V 14 - Exception occured: The "--no-interaction" option does not exist.

### ISSUE THREAD

**Issue by planepix** [contao/contao-manager#222]
Danke für die nächste Version des CM!.

Der Manager wurde von V 13 auf V 14 aktualisiert.
Nach dem Klick auf „Pakete aktualisieren” wird folgender Fehler in der Konsole des CM ausgegeben:
```
--------------------------------------------------------
Exception occured: The "--no-interaction" option does not exist.
#0 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/www/htdocs/w00...')
#3 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/www/htdocs/w00...')
#4 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(252): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(964): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/htdocs/xxx/web/contao-manager.phar.php(55): require('phar:///www/htd...')
#12 {main}
Chained exception: The "--no-interaction" option does not exist.
#0 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Input/ArrayInput.php(134): Symfony\Component\Console\Input\ArrayInput->addLongOption('no-interaction', true)
#1 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Input/Input.php(55): Symfony\Component\Console\Input\ArrayInput->parse()
#2 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(210): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#4 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#5 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#6 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/www/htdocs/w00...')
#7 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/www/htdocs/w00...')
#8 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(252): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(964): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /www/htdocs/xxx/web/contao-manager.phar.php(55): require('phar:///www/htd...')
#16 {main}
--------------------------------------------------------
Process terminated with exit code 1
Reason: General error
```
Führe ich composer update via Konsole aus wird kein Fehler angezeigt.

Getestet bei allinkl, PHP 7.1 und 7.2, mit Contao 4.4.14 und 4.5.4.

**Comment by andre5tz** [comment]
Gleiches Problem bei webgo, PHP 7.1, mit Contao 4.4.14

**Comment by aschempp** [comment]
Der Fehler ist in der Beta15 behoben.

**Comment by delirius** [comment]
Danke! Bei mir funktioniert es nun wieder
