### ISSUE TITLE
Aktualisierung mit Fehler - PaletteManipulator

### ISSUE THREAD

**Issue by planepix** [contao/contao-manager#226]
Hallo zusammen,

beim Aktualisieren der Pakete wird folgender Fehler ausgegeben:
```

08:29:18 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'PaletteManipulator' not found" ["error" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'PaletteManipulator' not found"] []

In tl_page.php line 1987:
                                                                               
  Attempted to load class "PaletteManipulator" from the global namespace.      
  Did you forget a "use" statement for e.g. "Haste\Dca\PaletteManipulator" or  
   "Contao\CoreBundle\DataContainer\PaletteManipulator"?                       
                                                                               

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

--------------------------------------------------------
Exception occured: The command "/usr/bin/php72 '-q' '/www/htdocs/xxx/vendor/bin/contao-console' 'cache:warmup' '--env=prod'" failed.

Exit Code: 255(Unknown error)

Working directory: /www/htdocs/xxx

Output:
================

 // Warming up the cache for the prod environment with debug                    
 // false                                                                       



Error Output:
================
08:29:18 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'PaletteManipulator' not found" ["error" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'PaletteManipulator' not found"] []

In tl_page.php line 1987:
                                                                               
  Attempted to load class "PaletteManipulator" from the global namespace.      
  Did you forget a "use" statement for e.g. "Haste\Dca\PaletteManipulator" or  
   "Contao\CoreBundle\DataContainer\PaletteManipulator"?                       
                                                                               

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


#0 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/Tenside/Task/RebuildCacheTask.php(88): Tenside\Core\Task\AbstractCliSpawningTask->runProcess(Object(Symfony\Component\Process\Process))
#1 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/Tenside/Task/RebuildCacheTask.php(54): Contao\ManagerApi\Tenside\Task\RebuildCacheTask->runSymfonyCommand('cache:warmup', Array, 'prod')
#2 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Contao\ManagerApi\Tenside\Task\RebuildCacheTask->doPerform()
#3 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/www/htdocs/w00...')
#4 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/www/htdocs/w00...')
#5 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(252): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(964): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///www/htdocs/xxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(148): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///www/htdocs/xxx/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/htdocs/xxx/web/contao-manager.phar.php(55): require('phar:///www/htd...')
#13 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

Contao 4.4.14
Hoster: allinkl
PHP 7.2.1

**Comment by fritzmg** [comment]
I guess this is the cause: https://github.com/ausi/contao-slug-backport/issues/2#issuecomment-366614695

**Comment by planepix** [comment]
Thanx a lot - after remove this bundle and run an update the website is back.

**Comment by ausi** [comment]
Fixed in version 1.0.3

**Comment by frontendschlampe** [comment]
confirm
