### ISSUE TITLE
Fehlermeldungen seit Contao-Manager-Update

### ISSUE THREAD

**Issue by petrad** [contao/contao-manager#229]
Nach dem automatischen Contao-Manager-Update erscheint nur noch "Lade Konsolentask..." und keine Konsolenausgabe mehr. 

Hoster: Webhostone
PHP: 7.1.13
Contao: 4.4
error.log:
```
[20-Feb-2018 19:04:09 Europe/Berlin] [2018-02-20 19:04:09] app.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "PUT /api/task/status" (from "http://xxx.de/contao-manager.phar.php/")" at phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/EventListener/RouterListener.php line 144 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"PUT /api/task/status\" (from \"http://xxx.de/contao-manager.phar.php/\") at phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/EventListener/RouterListener.php:144, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at phar:///home/www/xxx/web/contao-manager.phar.php/api/Resources/cache/apiProdProjectContainerUrlMatcher.php:354)"} []
[20-Feb-2018 19:04:17 Europe/Berlin] [2018-02-20 19:04:17] request.INFO: Matched route "task". {"route":"task","route_parameters":{"_controller":"Contao\\ManagerApi\\Controller\\TaskController","_route":"task"},"request_uri":"http://xxx.de/contao-manager.phar.php/api/task?_locale=de","method":"PATCH"} []
[20-Feb-2018 19:04:17 Europe/Berlin] [2018-02-20 19:04:17] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":2} []
[20-Feb-2018 19:04:17 Europe/Berlin] [2018-02-20 19:04:17] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[20-Feb-2018 19:04:17 Europe/Berlin] [2018-02-20 19:04:17] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[20-Feb-2018 19:04:17 Europe/Berlin] [2018-02-20 19:04:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[20-Feb-2018 19:04:17 Europe/Berlin] [2018-02-20 19:04:17] app.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: "Symfony\Component\Security\Core\Exception\AccessDeniedException: Access Denied. in phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall/AccessListener.php:68 Stack trace: #0 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(83): Symfony\Component\Security\Http\Firewall\AccessListener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #1 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(56): Symfony\Component\Security\Http\Firewall->handleRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), Object(Symfony\Component\DependencyInjection\Argument\RewindableGenerator)) #2 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security-bundle/EventListener/FirewallListener.php(48): Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\Bundle\SecurityBundle\EventListener\FirewallListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #4 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #5 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 phar:///home/www/xxx/web/contao-manager.phar.php/web/api.php(21): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 [internal function]: unknown() #10 /home/www/xxx/web/contao-manager.phar.php(99): Phar::webPhar(NULL, 'index.html', '', Array, 'rewrites') #11 {main}" at phar:///home/www/xxx/web/contao-manager.phar.php/api/EventListener/ExceptionListener.php line 111 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\UnauthorizedHttpException(code: 0): Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException: Access Denied. in phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall/AccessListener.php:68\nStack trace:\n#0 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(83): Symfony\\Component\\Security\\Http\\Firewall\\AccessListener->handle(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#1 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(56): Symfony\\Component\\Security\\Http\\Firewall->handleRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), Object(Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator))\n#2 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/security-bundle/EventListener/FirewallListener.php(48): Symfony\\Component\\Security\\Http\\Firewall->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#3 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\\Bundle\\SecurityBundle\\EventListener\\FirewallListener->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#4 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#5 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#6 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#7 phar:///home/www/xxx/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#8 phar:///home/www/xxx/web/contao-manager.phar.php/web/api.php(21): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#9 [internal function]: unknown()\n#10 /home/www/xxx/web/contao-manager.phar.php(99): Phar::webPhar(NULL, 'index.html', '', Array, 'rewrites')\n#11 {main} at phar:///home/www/xxx/web/contao-manager.phar.php/api/EventListener/ExceptionListener.php:111)"} []
```

Jemand eine Idee, welche(n) Befehl(e) zur Reparatur ausgeführt werden können? 
Vielen Dank im Voraus, Petra

**Comment by petrad** [comment]
Habe auf dem selben Server Contao 4.4 neu eingerichtet und die notwendigen Daten rüberkopiert, nun läuft der Contao-Manager wieder. Aber vielleicht helfen obige Fehlermeldungen trotzdem weiter.

**Comment by aschempp** [comment]
This will be fixed in the next release.

**Comment by Stefko** [comment]
I'm using Beta16 now, but the problem still exists (Contao 4.4.14)
- as I described at #232 on my local machine (see error.log below)
- 1&1 Unlimited Pro (PHP7.1.13)
- 1&1 Unlimted Plus (PHP7.1.13)

Error.log of my local installation:
 [22-Feb-2018 13:45:54 Europe/Berlin] [2018-02-22 13:45:54] app.WARNING: Forking disabled by configuration, execution will block until the command has finished. [] []
[22-Feb-2018 13:45:54 Europe/Berlin] [2018-02-22 13:45:54] app.ERROR: Attempted to run task background-process twice. [] []
[22-Feb-2018 13:45:54 Europe/Berlin] [2018-02-22 13:45:54] app.ERROR:  [] []
[22-Feb-2018 13:45:54 Europe/Berlin] [2018-02-22 13:45:54] console.DEBUG: Command "tenside:runtask background-process -v --no-interaction" exited with code "1" {"command":"tenside:runtask background-process -v --no-interaction","code":1} []
[22-Feb-2018 13:56:40 Europe/Berlin] [2018-02-22 13:56:40] request.INFO: Matched route "task". {"route":"task","route_parameters":{"_controller":"Contao\\ManagerApi\\Controller\\TaskController","_route":"task"},"request_uri":"https://christoph.local/contao-manager.phar.php/api/task?_locale=de","method":"PATCH"} []
[22-Feb-2018 13:56:40 Europe/Berlin] [2018-02-22 13:56:40] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":2} []
[22-Feb-2018 13:56:40 Europe/Berlin] [2018-02-22 13:56:40] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[22-Feb-2018 13:56:40 Europe/Berlin] [2018-02-22 13:56:40] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"api","authenticator":"Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[22-Feb-2018 13:56:40 Europe/Berlin] [2018-02-22 13:56:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[22-Feb-2018 13:56:40 Europe/Berlin] [2018-02-22 13:56:40] app.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: "Symfony\Component\Security\Core\Exception\AccessDeniedException: Access Denied. in phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall/AccessListener.php:68 Stack trace: #0 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(83): Symfony\Component\Security\Http\Firewall\AccessListener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #1 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(56): Symfony\Component\Security\Http\Firewall->handleRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), Object(Symfony\Component\DependencyInjection\Argument\RewindableGenerator)) #2 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security-bundle/EventListener/FirewallListener.php(48): Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\Bundle\SecurityBundle\EventListener\FirewallListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #4 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #5 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/web/api.php(21): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 [internal function]: unknown() #10 /Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php(99): Phar::webPhar(NULL, 'index.html', '', Array, 'rewrites') #11 {main}" at phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/api/EventListener/ExceptionListener.php line 111 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\UnauthorizedHttpException(code: 0): Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException: Access Denied. in phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall/AccessListener.php:68\nStack trace:\n#0 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(83): Symfony\\Component\\Security\\Http\\Firewall\\AccessListener->handle(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#1 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security/Http/Firewall.php(56): Symfony\\Component\\Security\\Http\\Firewall->handleRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), Object(Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator))\n#2 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/security-bundle/EventListener/FirewallListener.php(48): Symfony\\Component\\Security\\Http\\Firewall->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#3 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\\Bundle\\SecurityBundle\\EventListener\\FirewallListener->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#4 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#5 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#6 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#7 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#8 phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/web/api.php(21): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#9 [internal function]: unknown()\n#10 /Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php(99): Phar::webPhar(NULL, 'index.html', '', Array, 'rewrites')\n#11 {main} at phar:///Users/Stefko/Documents/htdocs/christoph.local/web/contao-manager.phar.php/api/EventListener/ExceptionListener.php:111)"} []

**Comment by aschempp** [comment]
> [20-Feb-2018 19:04:09 Europe/Berlin] [2018-02-20 19:04:09] app.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "PUT /api/task/status" (from "http://xxx.de/contao-manager.phar.php/")" 

That's the message I fixed in beta16.

**Comment by fkaminski** [comment]
Habe das Problem jetzt auch. Beim Aufruf will der CM auf die beta17 updaten. Das Konsolenfenster startet ohne Konsolenausgabe und das wars. Wenn ich den Manager neu aufrufe erhalte ich das Konsolenfenster inkl. Ausgabe mit der Angabe das alles erfolgreich beendet wurde ...

Hoster: hostingwerk
```
[21-Feb-2018 09:18:34 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Event\ConsoleTerminateEvent' not found in phar:///var/virtual/bo-fk/public/_contao45/web/contao-manager.phar.php/vendor/symfony/console/Application.php:901
Stack trace:
#0 phar:///.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Terminal42\BackgroundProcess\Command\ProcessRunnerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///.../web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///.../web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput in phar:///.../web/contao-manager.phar.php/vendor/symfony/console/Application.php on line 901
[10-Apr-2018 08:25:51 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in phar:///.../web/contao-manager.phar.php/vendor/symfony/debug/ErrorHandler.php:533
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in phar:///.../web/contao-manager.phar.php/vendor/symfony/debug/ErrorHandler.php on line 533
[10-Apr-2018 08:25:51 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in phar:///.../web/contao-manager.phar.php/vendor/symfony/debug/ErrorHandler.php:656
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler::handleFatalError()
```

**Comment by stefanschleich** [comment]
Habe das Problem auch in einer frisch installierten Contao Managed Edition (4.4.17). Der Manager läuft auf 1.0.0-beta17. Hosting ebenfalls bei hostingwerk.

Hier die Files, die während der Installation eines Bundles erstellt und nach Reload des Managers wieder gelöscht wurden:

/contao-manager
[background-process.get.json](https://github.com/contao/contao-manager/files/1919038/background-process.get.json.txt)
[background-process.set.json](https://github.com/contao/contao-manager/files/1919039/background-process.set.json)
[tenside-task-background-process.json.txt](https://github.com/contao/contao-manager/files/1919040/tenside-task-background-process.json)
[tenside-tasks.json.txt](https://github.com/contao/contao-manager/files/1919041/tenside-tasks.json.txt)

/contao-manager/logs
[error.log](https://github.com/contao/contao-manager/files/1919036/error.log)
[task-background-process.log](https://github.com/contao/contao-manager/files/1919037/task-background-process.log)

**Comment by Stefko** [comment]
Wie ich hier (*) schon schrieb, tritt das Problem nicht auf, wenn in `/contao-manager/logs` eine leere `task-background-process.log` angelegt wird.
Kann es sein, dass hier das Timing etwas aus dem Ruder läuft und das Konsolenfenster versucht auf diese Datei zuzugreifen bevor diese tatsächlich angelegt ist?

(*) https://community.contao.org/de/showthread.php?69868-Paketmanager-funktioniert-nicht-(4-4-14)-Keine-Reaktion-in-der-Konsole-(Hostpoint)&p=466062&viewfull=1#post466062

**Comment by leofeyer** [comment]
Das Problem auf dem Hostingwerk-Server lässt sich durch einen Restart des PHP-FPM-Prozesses beheben (entweder durch Änderung einer Einstellung im Control-Panel oder über den Support). Ich habe allerdings noch nicht herausgefunden, wodurch es verursacht wird.
