### ISSUE TITLE
Issues after Updating to V1.1.0 / V1.1.1

### ISSUE THREAD

**Issue by mr2017x** [contao/contao-manager#366]
I Guys,

after Updating today and let checks go through my environment i get following:

PHP Fatal error:  Uncaught Error: Class 'Contao\CommentsBundle\ContaoManager\Plugin' not found in /var/www/contao/vendor/contao/manager-plugin/src/PluginLoader.php:56
Stack trace:
#0 /var/www/contao/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(110): Contao\ManagerPlugin\PluginLoader->__construct()
#1 /var/www/contao/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(136): Contao\ManagerBundle\HttpKernel\ContaoKernel->getPluginLoader()
#2 /var/www/contao/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(228): Contao\ManagerBundle\HttpKernel\ContaoKernel->getBundleLoader()
#3 /var/www/contao/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(62): Contao\ManagerBundle\HttpKernel\ContaoKernel->addBundlesFromPlugins(Array)
#4 /var/www/contao/vendor/symfony/http-kernel/Kernel.php(405): Contao\ManagerBundle\HttpKernel\Cont in /var/www/contao/vendor/contao/manager-plugin/src/PluginLoader.php on line 56
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

An error occurred while executing the "contao:install-web-dir" command: PHP  
   Fatal error:  Uncaught Error: Class 'Contao\CommentsBundle\ContaoManager\P  
  lugin' not found in /var/www/contao/vendor/cont  
  ao/manager-plugin/src/PluginLoader.php:56                                    
  Stack trace:                               

before everything run smooth. so may you can tell me were to aid the system.

**Comment by aschempp** [comment]
Where do you get that? Can you post a screenshot of the error message?

**Comment by aschempp** [comment]
Closing due to inactivity.
