### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by aschempp** [contao/contao-manager#66]
Windows is currently not a supported platform, first needs to be tested.

**Comment by Schneetiger** [comment]
Error 501 under Win 8.1 using Xampp while installing the contao-manager 1.0.0-beta7
ERROR 501 This version of Contao Manager is currently not supported on Windows. (see headline; just a hint)

**Comment by CMSworker** [comment]
Hello @aschempp , could you please add some notes in this issue about the required steps to make the Contao Manager compatible with Windows, like a roadmap for Windows support or something similar? What is the current Windows support state and what needs to be done to support Windows?

You wrote "needs to be tested" - what kind of tests do you have in mind? I could try to help testing, but I'm no coding expert so I'm not sure if my feedback will be useful. Currently the Manager is only throwing the error message so "testing" isn't possible at all. What problems do you expect and what parts of the manager needs to be changed oder extended to support Windows?

I'm using XAMPP with PHP 7.1 on Windows 10 for local CMS preparation (Contao 4.4 LTS) before publishing it online and would be happy using the Manager on this non-linux "development" environment as well instead of the CMD Composer ... Thank you very much for your efford.

**Comment by aschempp** [comment]
If I would know the required steps, I would probably already have done them ;-)
I have no idea if our general setup currently works on Windows. @bezin did several pull requests, but I don't know if anything's missing.

Basically, the best would be if a developer can check out the source code and get the manager to work on Windows, figuring out what there is to do…

**Comment by AgenceUpMotion** [comment]
Des nouvelles ?

**Comment by Schneetiger** [comment]
Hi Andreas, tried to install Contao 4 under Win 8.1and Xampp but it didn't work. Forgot the error Code, think it was 136. Now I will try it with Contao-Check tomorrow.

Greetings
Detlef Rimböck

⁣Gesendet mit BlueMail ​

**Comment by bezin** [comment]
Hi there, 

I would like to pick up on this: The several smaller fixes I added did add a little more support to Windows, but it also raised other issues ;) The situation still is, that, the installation runs quite smoothly on my local machine, but fails to move the whole installation after installing because of relative symlinks. I reported that in #99 and did not have the time yet to further investigate on this. Yet I would like to solve this, but stillt need to wrap my head around the whole Contao Manager and Tenside setup.

I would love to discuss this at the upcoming Contao Camp, if anybody is interested ;)

Cheerio.

**Comment by aschempp** [comment]
> I would love to discuss this at the upcoming Contao Camp, if anybody is interested ;)

Me too! 😎

**Comment by Schneetiger** [comment]
Hi together,

I am not a developer and can't take part at the Contao Camp this year. But I have the same problem when I want to install Contao on XAMPP under Windows. The installation get's interrupted with the hint of missing symlinks.
Maybe this message is helpful too.

Greetings
Detlef Rimböck

⁣Gesendet mit BlueMail ​

**Comment by do-while** [comment]
Wäre sehr schade, wenn es ohne Windows-Support bliebe.
Bin auf dem Camp dabei, wenn wir drüber reden wollen.
Bis bald ...

**Comment by bezin** [comment]
@Schneetiger Are you talking about installing Contao 4 in general or installing it via the Contao Manager? If in general, it is probably because you do not run Composer from an elevated command prompt, i. e. without admin privileges.

**Comment by Schneetiger** [comment]
Thanks a lot for answering so quickly. Well, I am not sure, which I did. I will try it again and tell you soon.
 

Gesendet: Mittwoch, 08. November 2017 um 20:14 Uhr
Von: "Benedict Zinke" <notifications@github.com>
An: contao/contao-manager <contao-manager@noreply.github.com>
Cc: Schneetiger <dmr01@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [contao/contao-manager] Windows Support (#66)


@Schneetiger Are you talking about installing Contao 4 in general or installing it via the Contao Manager? If in general, it is probably because you do not run Composer from an elevated command prompt, i. e. without admin privileges.

**Comment by bezin** [comment]
In the session at the Contao Camp, we figured out a possible workaround that enables users to install Contao 4 on a Windows machine without command line and manage packages/extensions via the Manager. Installing Contao 4 on a Windows machine via the manager, however, is a different story and not easily fixed. 

For the record: I was able to install and remove packages via the Contao Manager on a windows machine 🥂 🎉 🍻 

But there are also some issues, that I will post separately and reference here. To have the cleanest testing environment, I downloaded the [Windows 10 virtual testing machine ](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and set it up it with [the latest XAMPP](https://www.apachefriends.org/xampp-files/7.1.11/xampp-win32-7.1.11-0-VC14-installer.exe). I compiled a custom contao-manager.phar that runs on Windows. If anybody else is interested in testing this on his/her local Windows machine, I can provide you with the PHAR. 

All the changes I did are pushed to [windows-compat in my fork](https://github.com/bezin/contao-manager/tree/windows-compat).

**Comment by Schneetiger** [comment]
Hi Benedikt,

thanks a lot for your comment. Yes I am very interested on your compiled phar.
Would be nice getting it from you.
I just switched over to Win 10 but I did not work with the Virtual Machine yet.

Parallel to Windows I will install Linux Mint and Xampp and Rey to install and run Contao 4.
Thanks for helping.

Greetings
Detlef Rimböck

⁣Gesendet mit BlueMail ​

**Comment by bezin** [comment]
Here you go: http://contao.presentprogressive.de/contao-manager-win-compat.zip

**Comment by JzJad** [comment]
Would like it to try and run regardless of the platform, using a little bash and composer on windows is simple enough and I have a hand full of applications not supported on windows working with IIS, for now will test the windows manager thanks!

**Comment by fritzmg** [comment]
@bezin what kind of things are changed in your Windows compatible version?

I just wanted to use the Contao Manager to search for packages under Windows. However, the Contao Manager currently refuses to do anything further, if Windows was detected as the platform. Does really _nothing_ work currently under Windows or is it just the installation? If it's just the installation, then the Contao Manager should allowed to be run under Windows in already existing Contao Installations.

**Comment by bezin** [comment]
With my PHAR you can install and remove packages, as I wrote above :) But the only changes I did are already implemented in c08257c213ba5c1cc369f1e60e8b30e18deacf22. So the only difference between my PHAR and the original archive is the OS check ;)

**Comment by Schneetiger** [comment]
Thanks to all of you for your hard work on the Contao-Manager. For time issues I haven't been able to test it so far. Will do it soon.
Merry Christmas time all of you.

Kind regards

Detlef Rimböck

⁣Gesendet mit BlueMail ​

**Comment by do-while** [comment]
Hallo Andreas,

ist es möglich, die Windows-Sperre zu umgehen?

Ich würde gern auf Windows etwas testen und gucken, ob es lauffähig zu machen geht. 
Idee wäre dass man den Aufruf vom Contao Manager mit einem Aufrufparameter oder irgendwo mit einem Dateieintrag umschiffen kann.
Oder gibt es da schon was?

**Comment by zonky2** [comment]
@bezin I just try your zip from https://github.com/contao/contao-manager/issues/66#issuecomment-345515541 but...

```
<br /> <b>Fatal error</b>: Uncaught Symfony\Component\Filesystem\Exception\IOException: Cannot rename &quot;C:\laragon\www\c4-mm-test\contao-manager\cache\api1179.tmp&quot; to &quot;C:/laragon/www/c4-mm-test\contao-manager/cache/apiDevDebugProjectContainer.php&quot;. in phar://C:/laragon/www/c4-mm-test/web/contao-manager.phar.php/vendor/symfony/filesystem/Filesystem.php:289 Stack trace: 
#0 phar://C:/laragon/www/c4-mm-test/web/contao-manager.phar.php/vendor/symfony/filesystem/Filesystem.php(686): Symfony\Component\Filesystem\Filesystem-&gt;rename('C:\\laragon\\www\\...', 'C:/laragon/www/...', true) 
#1 phar://C:/laragon/www/c4-mm-test/web/contao-manager.phar.php/vendor/symfony/config/ResourceCheckerConfigCache.php(138): Symfony\Component\Filesystem\Filesystem-&gt;dumpFile('C:/laragon/www/...', '&lt;?php\n\nuse Symf...', NULL) 
#2 phar://C:/laragon/www/c4-mm-test/web/contao-manager.phar.php/vendor/symfony/http-kernel/Kernel.php(762): Symfony\Component\Config\ResourceCheckerConfigCache-&gt;write('&lt;?php\n\nuse Symf...', Array) 
#3 phar://C:/laragon/www/c4-mm-test/web/contao in <b>phar://C:/laragon/www/c4-mm-test/web/contao-manager.phar.php/vendor/symfony/filesystem/Filesystem.php</b> on line <b>289</b><br />
```

**Comment by aschempp** [comment]
@do-while es gibt kein entsprechendes Flag. Wenn du auf Windows *testen und lauffähig machen* willst, müsstest du die Entwickler-Version (GIT Repo auschecken etc.) nehmen.

**Comment by Schneetiger** [comment]
Hi Yannick,
super! Danke für Eure tolle Arbeit. Bedeutet das, wir können den CM jetzt auch unter Win/Xampp problemlos nutzen; also C4 installieren?

⁣Freundliche Grüße
Detlef Rimböck

Gesendet mit BlueMail ​

**Comment by Toflar** [comment]
Ja :)

**Comment by iGweb** [comment]
thanks, i will test that :-)
